# <font color='blue'>Operações Vetoriais e Manipulação de Matrizes com NumPy</font>

In [1]:
# Instalando o NumPy
!pip install -q numpy==2.3.2

In [2]:
# Importando a biblioteca Numpy
import numpy as np

# Comparando Numpy com Python puro #

In [3]:
import math
import time

In [4]:
# Criando uma lista (vetor) com Numpy de 10milhões de itens
precos_np = np.random.rand(10_000_000)
type(precos_np)

numpy.ndarray

In [5]:
# criando uma lista (Python puro)
preco_list = list(precos_np)
type(preco_list)

list

In [6]:
# Operação com Numpy
t0 = time.time()
desc = precos_np * 0.90     # preco com desconto de 10%
final = desc + 5
raiz = np.sqrt(precos_np)
print("Numpy:", time.time() - t0, "segundos")

Numpy: 0.2714192867279053 segundos


In [7]:
# Mesma operação com Python puro
t0 = time.time()
desc = [x * 0.90 for x in preco_list]
final = [x + 5 for x in desc]
raiz = [math.sqrt(x) for x in preco_list]
print("Python Puro:", time.time() - t0, "segundos")


Python Puro: 10.117407321929932 segundos


In [8]:
# Para 10 milhões de valores, o NumPy normalmente é muito mais rápido. Mas para poucos valores, o uso de loops com Python puro pode sair na frente porque o overhead do NumPy pesa mais que o ganho para poucos registros.

#✅ Resumindo:

    # Poucos elementos → Loops Python podem ser mais rápidos (overhead do NumPy é maior).
    # Muitos elementos → NumPy é muito mais rápido e escalável.

# É pela sua velocidade, que NumPy é amplamente usado em projetos de Ciência de Dados, Machine Learning e IA.

# O Objeto ndarray #

In [9]:
# Criando um array de 1 dimensão (vetor) a partir de uma lista Python
vetor = np.array([17, 21, 100, 34])
print("\nVetor (Array 1D):\n")
print(vetor)


Vetor (Array 1D):

[ 17  21 100  34]


In [15]:
# Verificando atributos
print("Formato (shape) do vetor:", vetor.shape)
print("Número de dimensões (ndim) do vetor:", vetor.ndim)
print("Número total de elementos (size) do vetor", vetor.size)

Formato (shape) do vetor: (4,)
Número de dimensões (ndim) do vetor: 1
Número total de elementos (size) do vetor 4


In [16]:
# Criando um array de 2 dimensões (matriz) a partir de uma lista de listas
matriz = np.array([[1, 2, 3],[4, 5, 6]])
print("\nMatriz (Array 2D):\n")
print(matriz)


Matriz (Array 2D):

[[1 2 3]
 [4 5 6]]


In [19]:
# Verificando atributos
print("Formato (shape) da matriz:", matriz.shape)   # (linhas, colunas)
print("Número de dimensões (ndim) da matriz:", matriz.ndim)
print("Número total de elementos (size) da matriz:", matriz.size)

Formato (shape) da matriz: (2, 3)
Número de dimensões (ndim) da matriz: 2
Número total de elementos (size) da matriz: 6


In [23]:
# Criando um array 3D usando np.arange()
arr = np.arange(24).reshape(4, 3, 2)   # (profundidade, linhas, colunas) ou (altura, largura, canais) para imagens
print("\nArray (Array 3D):\n")
print(arr)


Array (Array 3D):

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [22]:
# Verificando atributos
print("Formato (shape) do array:", arr.shape)
print("Número de dimensões (ndim) do array:", arr.ndim)
print("Número total de elementos (size) do array:", arr.size)

Formato (shape) do array: (4, 3, 2)
Número de dimensões (ndim) do array: 3
Número total de elementos (size) do array: 24


In [ ]:
# Tensor 3D -- Em Machine Learning e computação numérica, um tensor de ordem 3 é, de fato, um array 3D.

In [25]:
# Array 4D com valores sequenciais de 0 a 119 organizado em 2x3x4x5
tensor_4d = np.arange(120).reshape(2, 3, 4, 5)
print(tensor_4d)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [29]:
# Verificando atributos importantes do array
print("Formato (shape) do array:", tensor_4d.shape)
print("Número de dimensões (ndim) do array:", tensor_4d.ndim)
print("Número total de elementos (size) do array:", tensor_4d.size)

Formato (shape) do array: (2, 3, 4, 5)
Número de dimensões (ndim) do array: 4
Número total de elementos (size) do array: 120
