# <font color='blue'>Operações Vetoriais e Manipulação de Matrizes com NumPy</font>

In [1]:
# Instalando o NumPy
!pip install -q numpy==2.3.2

In [2]:
# Importando a biblioteca Numpy
import numpy as np

# Comparando Numpy com Python puro #

In [3]:
import math
import time

In [4]:
# Criando uma lista (vetor) com Numpy de 10milhões de itens
precos_np = np.random.rand(10_000_000)
type(precos_np)

numpy.ndarray

In [5]:
# criando uma lista (Python puro)
preco_list = list(precos_np)
type(preco_list)

list

In [6]:
# Operação com Numpy
t0 = time.time()
desc = precos_np * 0.90     # preco com desconto de 10%
final = desc + 5
raiz = np.sqrt(precos_np)
print("Numpy:", time.time() - t0, "segundos")

Numpy: 0.17513275146484375 segundos


In [7]:
# Mesma operação com Python puro
t0 = time.time()
desc = [x * 0.90 for x in preco_list]
final = [x + 5 for x in desc]
raiz = [math.sqrt(x) for x in preco_list]
print("Python Puro:", time.time() - t0, "segundos")


Python Puro: 5.968168020248413 segundos


Para 10 milhões de valores, o NumPy normalmente é muito mais rápido. Mas para poucos valores, o uso de loops com Python puro pode sair na frente porque o overhead do NumPy pesa mais que o ganho para poucos registros.

✅ Resumindo:

    Poucos elementos → Loops Python podem ser mais rápidos (overhead do NumPy é maior).
    
    Muitos elementos → NumPy é muito mais rápido e escalável.

É pela sua velocidade, que NumPy é amplamente usado em projetos de Ciência de Dados, Machine Learning e IA.

# O Objeto ndarray #

In [8]:
# Criando um array de 1 dimensão (vetor) a partir de uma lista Python
vetor = np.array([17, 21, 100, 34])
print("\nVetor (Array 1D):\n")
print(vetor)


Vetor (Array 1D):

[ 17  21 100  34]


In [9]:
# Verificando atributos
print("Formato (shape) do vetor:", vetor.shape)
print("Número de dimensões (ndim) do vetor:", vetor.ndim)
print("Número total de elementos (size) do vetor", vetor.size)

Formato (shape) do vetor: (4,)
Número de dimensões (ndim) do vetor: 1
Número total de elementos (size) do vetor 4


In [10]:
# Criando um array de 2 dimensões (matriz) a partir de uma lista de listas
matriz = np.array([[1, 2, 3],[4, 5, 6]])
print("\nMatriz (Array 2D):\n")
print(matriz)


Matriz (Array 2D):

[[1 2 3]
 [4 5 6]]


In [11]:
# Verificando atributos
print("Formato (shape) da matriz:", matriz.shape)   # (linhas, colunas)
print("Número de dimensões (ndim) da matriz:", matriz.ndim)
print("Número total de elementos (size) da matriz:", matriz.size)

Formato (shape) da matriz: (2, 3)
Número de dimensões (ndim) da matriz: 2
Número total de elementos (size) da matriz: 6


In [12]:
# Criando um array 3D usando np.arange()
arr = np.arange(24).reshape(4, 3, 2)   # (profundidade, linhas, colunas) ou (altura, largura, canais) para imagens
print("\nArray (Array 3D):\n")
print(arr)


Array (Array 3D):

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [13]:
# Verificando atributos
print("Formato (shape) do array:", arr.shape)
print("Número de dimensões (ndim) do array:", arr.ndim)
print("Número total de elementos (size) do array:", arr.size)

Formato (shape) do array: (4, 3, 2)
Número de dimensões (ndim) do array: 3
Número total de elementos (size) do array: 24


Tensor 3D -- Em Machine Learning e computação numérica, um tensor de ordem 3 é, de fato, um array 3D.

In [14]:
# Array 4D com valores sequenciais de 0 a 119 organizado em 2x3x4x5
tensor_4d = np.arange(120).reshape(2, 3, 4, 5)
print(tensor_4d)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [15]:
# Verificando atributos importantes do array
print("Formato (shape) do array:", tensor_4d.shape)
print("Número de dimensões (ndim) do array:", tensor_4d.ndim)
print("Número total de elementos (size) do array:", tensor_4d.size)

Formato (shape) do array: (2, 3, 4, 5)
Número de dimensões (ndim) do array: 4
Número total de elementos (size) do array: 120


# Tipos de Dados do Numpy #

Diferente das listas em Python, os array Numpy são homogêneos; todos os elementos 
devem ter o mesmo tipo de dado. Isso é fundamental para a peformance.

In [16]:
# Numpy infere o tipo de dado automaticamente
arr_inteiros = np.array([1, 2, 3])
print("Tipo de dado (inteiros):", arr_inteiros.dtype)

Tipo de dado (inteiros): int64


In [17]:
# Numpy infere o tipo de dado automaticamente
arr_float = np.array([1.0, 2.0, 3.0])
print("Tipo de dado (inteiros):", arr_float.dtype)

Tipo de dado (inteiros): float64


In [18]:
# Mas podemos especificar o tipo de dado durante a criação
arr_float = np.array([1, 2, 3], dtype = np.float64)
print("Tipo de dado (float64):", arr_float.dtype)
print("Array float:", arr_float)

Tipo de dado (float64): float64
Array float: [1. 2. 3.]


In [19]:
# Conversão para int64
arr_int = arr_float.astype(np.int64)
print("Tipo convertido:", arr_int.dtype)
print("Array convertido:", arr_int)

Tipo convertido: int64
Array convertido: [1 2 3]


In [20]:
dados = np.arange(16).reshape(4, 4)
print(dados)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [21]:
dados_cortados = dados[:1, :3]
print(dados_cortados)

[[0 1 2]]


# 6. Agregações Estatísticas # 

Estatística descritivas de um conjunto de dados que é muito otimizada no NumPy

In [22]:
# Notas de 3 alunos em 4 provas
notas = np.array([
    [8.5, 7.0, 9.2, 6.5],
    [5.5, 6.8, 7.5, 8.0],
    [9.5, 9.0, 8.8, 10.0]
])

In [24]:
print("\nMatriz de Notas:\n")
print(notas)


Matriz de Notas:

[[ 8.5  7.   9.2  6.5]
 [ 5.5  6.8  7.5  8. ]
 [ 9.5  9.   8.8 10. ]]


In [25]:
type(notas)

numpy.ndarray

In [29]:
# Agregações na matriz inteira
print(f"\nMédia geral da turma: {notas.mean():.2f}")
print(f"Nota máxima da turma: {notas.max()}")
print(f"Nota mínima da turma: {notas.min()}")
print(f"Soma de todas as notas: {notas.sum()}\n")


Média geral da turma: 8.03
Nota máxima da turma: 10.0
Nota mínima da turma: 5.5
Soma de todas as notas: 96.3



In [32]:
# Agregações por eixo (axis)
# Média de cada aluno (agregando nas colunas, axis = 1) arredondando para duas casas decimais
media_por_aluno = notas.mean(axis = 1).round(2)
print(f"\nMédia de cada aluno: {media_por_aluno}")


Média de cada aluno: [7.8  6.95 9.32]


In [34]:
# Média de cada prova (agregando nas linhas, axis = 0) arredondando para duas casas decimais
media_por_prova = notas.mean(axis = 0).round(2)
print(f"\nMédia de cada prova: {media_por_prova}")


Média de cada prova: [7.83 7.6  8.5  8.17]


# 7. Broadcasting e Operações Entre Arrays


Broadcasting: É o mecanismo que permite realizar operações aritméticas entre arrays de 
formas (shapes) diferentes. Sem precisar copiar ou replicar manualmente os dados.

Funciona expandindo automaticamente as dimensões de arrays menores para que fiquem
compatíveis com os maiores seguindo um conjunto de regras. Isso evita laços(loops)
explícitos e melhora muito a eficiência.

Ex: Se somar uma matriz 3x3 com um vetor de 3 elementos, o NumPy estica o vetor para
que cada linha da matriz receba a soma correspondente elemento a elemento sem criar 
cópias extras na memória.

In [36]:
# Matriz 3x3
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [37]:
type(matriz)

numpy.ndarray

In [38]:
matriz.shape

(3, 3)

In [39]:
# Vetor 1D com 3 elementos
vetor = np.array([10, 20, 30])

In [40]:
type(vetor)

numpy.ndarray

In [41]:
vetor.shape

(3,)

SOMANDO OS VALORES DO VETOR AOS VALORES DE CADA LINHA DA MATRIZ

In [49]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
print(vetor)

[10 20 30]


In [51]:
# Broadcasting: o vetor é "expandido" para cada linha da matriz
resultado = matriz + vetor

In [54]:
print("\nMatriz original:\n", matriz)
print("\nVetor:\n", vetor)
print("\nResultado com broadcasting:\n", resultado)


Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Vetor:
 [10 20 30]

Resultado com broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [60]:
# Matriz com faturamento de 3 produtos em 4 meses
faturamento = np.array([
    [100, 110, 120, 130], # Produto A
    [200, 210, 220, 230], # Produto B
    [300, 310, 320, 330]  # Produto C
])

In [61]:
type(faturamento)

numpy.ndarray

In [62]:
# Shape
faturamento.shape

(3, 4)

In [63]:
# Vetor com um bônus (incetivo) para cada produto
bonus_por_produto = np.array([5, 10, 15])

In [64]:
type(bonus_por_produto)

numpy.ndarray

In [65]:
# Shape
bonus_por_produto.shape

(3,)

Adicionando um bônus a cada valor de faturamento, por linha. Ou seja, todos os itens
da primeira linha devem receber o bônus de 5, por exemplo, e assim por diante.

In [67]:
print("\nFaturamento:\n")
print(faturamento)
print("\nBônus por Produto:\n")
print(bonus_por_produto)


Faturamento:

[[100 110 120 130]
 [200 210 220 230]
 [300 310 320 330]]

Bônus por Produto:

[ 5 10 15]


In [69]:
# faturamento_com_bonus = faturamento + bonus_por_produto

In [70]:
# A variável acima apresenta um erro pois a forma de bonus_por_produto (3,) é
# incompatível com (3, 4) da matriz faturamento.
# Para a soma acontecer é necessário que bonus_por_produto tenha a forma (3, 1) para
# o broadcasting funcionar nas colunas.
bonus_formatado = bonus_por_produto.reshape(3, 1)


In [71]:
bonus_formatado.shape

(3, 1)

In [73]:
print("\nBônus por Produto:\n")
print(bonus_formatado)


Bônus por Produto:

[[ 5]
 [10]
 [15]]


In [75]:
# Pronto, broadcasting está funcionando.
faturamento_com_bonus = faturamento + bonus_formatado
print("\nFaturamento com Bônus (via Broadcasting):\n")
print(faturamento_com_bonus)


Faturamento com Bônus (via Broadcasting):

[[105 115 125 135]
 [210 220 230 240]
 [315 325 335 345]]


# 8. Manipulação de Formato de Arrays #

In [79]:
# Criando um array 1D com 12 elementos
dados_sequenciais = np.arange(12)
print(f"\nArray original (1D): {dados_sequenciais}")


Array original (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [82]:
# Remodelando para uma matriz 3x4
matriz3x4 = dados_sequenciais.reshape(3, 4)
print(f"\nMatriz 3x4:\n{matriz3x4}")


Matriz 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [85]:
# Transpondo a matriz (trocando linhas por colunas)
matriz_transposta = matriz3x4.T
print(f"\nMatriz Transposta (4x3):\n{matriz_transposta}")


Matriz Transposta (4x3):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [86]:
# Achatando a matriz de volta para um array 1D
array_achatado = matriz_transposta.flatten()
print(f"\nArray achatado (1D): {array_achatado}")


Array achatado (1D): [ 0  4  8  1  5  9  2  6 10  3  7 11]
